---
title: "Untitled"
author: "Jianmin Chen"
date: "2018年2月24日"
output: html_document
---
```{r}
library(tidyverse)
library(tidytext)
library(lubridate)
```

```{r}
words = read_csv('feature4jianmin.csv')
n=500
s1=tibble(word = words$word[order(words$V1,decreasing = TRUE)][1:n])
s2=tibble(word = words$word[order(words$V2,decreasing = TRUE)][1:n])
s3=tibble(word = words$word[order(words$V3,decreasing = TRUE)][1:n])
s4=tibble(word = words$word[order(words$V4,decreasing = TRUE)][1:n])
s5=tibble(word = words$word[order(words$V5,decreasing = TRUE)][1:n])

```

```{r}
date = read_csv('train_en2.csv')
# index = sample(nrow(date),100000,replace=FALSE)
index = c(1:nrow(date))
review = date[index,]
review1 <- date[index,] %>%
  select(text) %>%
  mutate(line = index)
review11 = review1[1:500000,]
t1 = Sys.time()
review21  <- review11 %>%
  unnest_tokens(word, text)
t2 = Sys.time()
t2-t1
review12 = review1[500001:1000001,]
review22  <- review12 %>%
  unnest_tokens(word, text)
review13 = review1[1000001:nrow(review1),]
review23  <- review13 %>%
  unnest_tokens(word, text)

review2 = bind_rows(review21, review22, review23)
x1 <- review2 %>%
  inner_join(s1, by = "word") %>%
  group_by(line) %>%
  summarise(count1 = n())
x2 <- review2 %>%
  inner_join(s2, by = "word") %>%
  group_by(line) %>%
  summarise(count2 = n())
x3 <- review2 %>%
  inner_join(s3, by = "word") %>%
  group_by(line) %>%
  summarise(count3 = n())
x4 <- review2 %>%
  inner_join(s4, by = "word") %>%
  group_by(line) %>%
  summarise(count4 = n())
x5 <- review2 %>%
  inner_join(s5, by = "word") %>%
  group_by(line) %>%
  summarise(count5 = n())
review3 <- review1 %>%
  full_join(x1, by = "line") %>%
  full_join(x2, by = "line") %>%
  full_join(x3, by = "line") %>%
  full_join(x4, by = "line") %>%
  full_join(x5, by = "line")
review3$count1[which(is.na(review3$count1))] = 0
review3$count2[which(is.na(review3$count2))] = 0
review3$count3[which(is.na(review3$count3))] = 0
review3$count4[which(is.na(review3$count4))] = 0
review3$count5[which(is.na(review3$count5))] = 0
new <- review3 %>%
  select(count1:count5)
######

new = data.frame(new)
colnames(new) = c('s1','s2','s3','s4','s5')


```

```{r}
review$date = apply(as.data.frame(review$date),1,FUN=year)
id1 = which(review$longitude< -100)
id2 = which(review$longitude> -100 & review$longitude< -25)
id3 = which(review$longitude> -25)
loc = rep(0,nrow(review))
loc1 = loc
loc1[id1] = 1
loc2 = loc
loc2[id2] = 1
loc3 = loc
loc3[id3] = 1
review = review %>% mutate(loc1=loc1,loc2=loc2,loc3=loc3)
# review = read_csv('test_final.csv')
review2 = cbind(review,new)
write_csv(review2,'train_final3.csv')
```
